-- Schema para o Supabase - EBSERH Study App
-- Execute este SQL no painel SQL do seu projeto Supabase

-- Tabela de Questões
CREATE TABLE IF NOT EXISTS questoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local INTEGER UNIQUE,  -- ID do SQLite local
    disciplina TEXT NOT NULL,
    semana INTEGER NOT NULL,
    nivel TEXT NOT NULL CHECK (nivel IN ('Básico', 'Alto', 'Pegadinha')),
    banca TEXT NOT NULL,
    enunciado TEXT NOT NULL,
    alternativas TEXT NOT NULL,  -- JSON com as alternativas
    resposta_correta TEXT NOT NULL,
    comentario TEXT NOT NULL,
    data_sincronizacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Desempenho
CREATE TABLE IF NOT EXISTS desempenho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local INTEGER UNIQUE,  -- ID do SQLite local
    questao_id_local INTEGER NOT NULL,  -- ID da questão no SQLite local
    resposta_usuario TEXT NOT NULL,
    acerto BOOLEAN NOT NULL,
    data_resposta TIMESTAMP WITH TIME ZONE,
    data_sincronizacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_questoes_id_local ON questoes(id_local);
CREATE INDEX IF NOT EXISTS idx_questoes_disciplina ON questoes(disciplina);
CREATE INDEX IF NOT EXISTS idx_questoes_semana ON questoes(semana);
CREATE INDEX IF NOT EXISTS idx_questoes_nivel ON questoes(nivel);

CREATE INDEX IF NOT EXISTS idx_desempenho_id_local ON desempenho(id_local);
CREATE INDEX IF NOT EXISTS idx_desempenho_questao_id_local ON desempenho(questao_id_local);
CREATE INDEX IF NOT EXISTS idx_desempenho_acerto ON desempenho(acerto);
CREATE INDEX IF NOT EXISTS idx_desempenho_data_resposta ON desempenho(data_resposta);

-- RLS (Row Level Security) - Opcional, se precisar de segurança por usuário
-- ALTER TABLE questoes ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE desempenho ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso (exemplo - ajuste conforme necessário)
/*
-- Permitir leitura pública das questões
CREATE POLICY "Questões públicas para leitura" ON questoes
    FOR SELECT USING (true);

-- Permitir inserção (apenas através da API)
CREATE POLICY "Inserir questões via API" ON questoes
    FOR INSERT WITH CHECK (true);

-- Permitir atualização (apenas através da API)
CREATE POLICY "Atualizar questões via API" ON questoes
    FOR UPDATE USING (true);

-- Permitir leitura pública do desempenho
CREATE POLICY "Desempenho público para leitura" ON desempenho
    FOR SELECT USING (true);

-- Permitir inserção de desempenho via API
CREATE POLICY "Inserir desempenho via API" ON desempenho
    FOR INSERT WITH CHECK (true);

-- Permitir atualização de desempenho via API
CREATE POLICY "Atualizar desempenho via API" ON desempenho
    FOR UPDATE USING (true);
*/

-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para atualizar updated_at
CREATE TRIGGER update_questoes_updated_at 
    BEFORE UPDATE ON questoes 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_desempenho_updated_at 
    BEFORE UPDATE ON desempenho 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Comentários sobre as tabelas
COMMENT ON TABLE questoes IS 'Tabela de questões de estudo sincronizadas do SQLite local';
COMMENT ON TABLE desempenho IS 'Tabela de desempenho dos usuários sincronizada do SQLite local';

-- Comentários sobre colunas importantes
COMMENT ON COLUMN questoes.id_local IS 'ID original da tabela SQLite local';
COMMENT ON COLUMN questoes.alternativas IS 'JSON com as alternativas da questão';
COMMENT ON COLUMN desempenho.id_local IS 'ID original da tabela SQLite local';
COMMENT ON COLUMN desempenho.questao_id_local IS 'ID da questão na tabela SQLite local';
